name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: |
          cd myfolio_client && flutter pub get
          cd ../myfolio_flutter && flutter pub get

      - name: Build Web
        run: |
          cd myfolio_flutter
          flutter build web --release --base-href "/my_folio/" --dart-define=API_URL=https://my-folio-a91r.onrender.com

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./myfolio_flutter/build/web
